export { default as PageSwitch } from './src/PageSwitch.vue'
export { default as PageSelect } from './src/PageSelect.vue'
export { default as PageInputNum } from './src/PageInputNum.vue'
export { default as ColorSelect } from './src/ColorSelect.vue'
export { default as PageLayout } from './src/PageLayout.vue'
